version: '2'

services:

  fileimportexport:
    image: fileimportexport
    restart: always
    hostname: localhost
    network_mode: "host"
    ports:
      - 8080:8080

  mongodb:
    image: mongo
    restart: always
    hostname: localhost
    network_mode: host
    container_name: mongo-tarstore
    ports:
      - 27017:27017